//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSach.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppSach.Resource.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logged in.
        /// </summary>
        internal static string afterDangNhap {
            get {
                return ResourceManager.GetString("afterDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string beforeDangNhap {
            get {
                return ResourceManager.GetString("beforeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string btnDangNhap {
            get {
                return ResourceManager.GetString("btnDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string btnHoTro {
            get {
                return ResourceManager.GetString("btnHoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type book.
        /// </summary>
        internal static string btnLoai {
            get {
                return ResourceManager.GetString("btnLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dels book history.
        /// </summary>
        internal static string btnLSSach {
            get {
                return ResourceManager.GetString("btnLSSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book publisher.
        /// </summary>
        internal static string btnNXB {
            get {
                return ResourceManager.GetString("btnNXB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string btnSach {
            get {
                return ResourceManager.GetString("btnSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string btnSua {
            get {
                return ResourceManager.GetString("btnSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create invoice.
        /// </summary>
        internal static string btnTaoHoaDon {
            get {
                return ResourceManager.GetString("btnTaoHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string btnThem {
            get {
                return ResourceManager.GetString("btnThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice information.
        /// </summary>
        internal static string btnXemHoaDon {
            get {
                return ResourceManager.GetString("btnXemHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string btnXoa {
            get {
                return ResourceManager.GetString("btnXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card.
        /// </summary>
        internal static string CCCD {
            get {
                return ResourceManager.GetString("CCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string chucvu {
            get {
                return ResourceManager.GetString("chucvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        internal static string chuyendoitaikhoan {
            get {
                return ResourceManager.GetString("chuyendoitaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string chuyenngonngu {
            get {
                return ResourceManager.GetString("chuyenngonngu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to convert.
        /// </summary>
        internal static string chuyentaikhoan {
            get {
                return ResourceManager.GetString("chuyentaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string diachi {
            get {
                return ResourceManager.GetString("diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string gioitinh {
            get {
                return ResourceManager.GetString("gioitinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a good day at work..
        /// </summary>
        internal static string HAPPY_WORK {
            get {
                return ResourceManager.GetString("HAPPY_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bill.
        /// </summary>
        internal static string hoadon {
            get {
                return ResourceManager.GetString("hoadon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string hoten {
            get {
                return ResourceManager.GetString("hoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customers.
        /// </summary>
        internal static string khachhang {
            get {
                return ResourceManager.GetString("khachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact admin.
        /// </summary>
        internal static string linkfb {
            get {
                return ResourceManager.GetString("linkfb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        internal static string luong {
            get {
                return ResourceManager.GetString("luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string matkhau {
            get {
                return ResourceManager.GetString("matkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string mssv {
            get {
                return ResourceManager.GetString("mssv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string ngaysinh {
            get {
                return ResourceManager.GetString("ngaysinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of entry to work.
        /// </summary>
        internal static string ngayvaolam {
            get {
                return ResourceManager.GetString("ngayvaolam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user controls.
        /// </summary>
        internal static string nhanvien {
            get {
                return ResourceManager.GetString("nhanvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string sanpham {
            get {
                return ResourceManager.GetString("sanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string taikhoan {
            get {
                return ResourceManager.GetString("taikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string tentaikhoan {
            get {
                return ResourceManager.GetString("tentaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string them {
            get {
                return ResourceManager.GetString("them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string trangcanhan {
            get {
                return ResourceManager.GetString("trangcanhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        internal static string trangchu {
            get {
                return ResourceManager.GetString("trangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee deletion history.
        /// </summary>
        internal static string txtLichSuXoaNV {
            get {
                return ResourceManager.GetString("txtLichSuXoaNV", resourceCulture);
            }
        }
    }
}
