//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSach.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppSach.Resource.VN", typeof(VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã đăng nhập.
        /// </summary>
        internal static string afterDangNhap {
            get {
                return ResourceManager.GetString("afterDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng.
        /// </summary>
        internal static string beforeDangNhap {
            get {
                return ResourceManager.GetString("beforeDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string btnDangNhap {
            get {
                return ResourceManager.GetString("btnDangNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hỗ trợ.
        /// </summary>
        internal static string btnHoTro {
            get {
                return ResourceManager.GetString("btnHoTro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        internal static string btnLoai {
            get {
                return ResourceManager.GetString("btnLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử xóa sách.
        /// </summary>
        internal static string btnLSSach {
            get {
                return ResourceManager.GetString("btnLSSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lưu.
        /// </summary>
        internal static string btnLuu {
            get {
                return ResourceManager.GetString("btnLuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NXB.
        /// </summary>
        internal static string btnNXB {
            get {
                return ResourceManager.GetString("btnNXB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sách.
        /// </summary>
        internal static string btnSach {
            get {
                return ResourceManager.GetString("btnSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sửa.
        /// </summary>
        internal static string btnSua {
            get {
                return ResourceManager.GetString("btnSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo hóa đơn.
        /// </summary>
        internal static string btnTaoHoaDon {
            get {
                return ResourceManager.GetString("btnTaoHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thêm.
        /// </summary>
        internal static string btnThem {
            get {
                return ResourceManager.GetString("btnThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thoát.
        /// </summary>
        internal static string btnThoat {
            get {
                return ResourceManager.GetString("btnThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT_Hóa đơn.
        /// </summary>
        internal static string btnXemHoaDon {
            get {
                return ResourceManager.GetString("btnXemHoaDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xóa.
        /// </summary>
        internal static string btnXoa {
            get {
                return ResourceManager.GetString("btnXoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCCD.
        /// </summary>
        internal static string CCCD {
            get {
                return ResourceManager.GetString("CCCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string chucvu {
            get {
                return ResourceManager.GetString("chucvu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đăng xuất.
        /// </summary>
        internal static string chuyendoitaikhoan {
            get {
                return ResourceManager.GetString("chuyendoitaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vn.
        /// </summary>
        internal static string chuyenngonngu {
            get {
                return ResourceManager.GetString("chuyenngonngu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chuyển đổi.
        /// </summary>
        internal static string chuyentaikhoan {
            get {
                return ResourceManager.GetString("chuyentaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quản trị.
        /// </summary>
        internal static string cv {
            get {
                return ResourceManager.GetString("cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string diachi {
            get {
                return ResourceManager.GetString("diachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string gioitinh {
            get {
                return ResourceManager.GetString("gioitinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc bạn một ngày làm việc tốt lành..
        /// </summary>
        internal static string HAPPY_WORK {
            get {
                return ResourceManager.GetString("HAPPY_WORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn.
        /// </summary>
        internal static string hoadon {
            get {
                return ResourceManager.GetString("hoadon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string hoten {
            get {
                return ResourceManager.GetString("hoten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to khách hàng.
        /// </summary>
        internal static string khachhang {
            get {
                return ResourceManager.GetString("khachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ Admin..
        /// </summary>
        internal static string linkfb {
            get {
                return ResourceManager.GetString("linkfb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương.
        /// </summary>
        internal static string luong {
            get {
                return ResourceManager.GetString("luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string matkhau {
            get {
                return ResourceManager.GetString("matkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN.
        /// </summary>
        internal static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSV.
        /// </summary>
        internal static string mssv {
            get {
                return ResourceManager.GetString("mssv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string ngaysinh {
            get {
                return ResourceManager.GetString("ngaysinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào làm.
        /// </summary>
        internal static string ngayvaolam {
            get {
                return ResourceManager.GetString("ngayvaolam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên.
        /// </summary>
        internal static string nhanvien {
            get {
                return ResourceManager.GetString("nhanvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHIẾU NHẬP.
        /// </summary>
        internal static string receipt {
            get {
                return ResourceManager.GetString("receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string sanpham {
            get {
                return ResourceManager.GetString("sanpham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT.
        /// </summary>
        internal static string sdt {
            get {
                return ResourceManager.GetString("sdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string taikhoan {
            get {
                return ResourceManager.GetString("taikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        internal static string tentaikhoan {
            get {
                return ResourceManager.GetString("tentaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa hồ sơ.
        /// </summary>
        internal static string trangcanhan {
            get {
                return ResourceManager.GetString("trangcanhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string trangchu {
            get {
                return ResourceManager.GetString("trangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lịch sử xóa nhân viên.
        /// </summary>
        internal static string txtLichSuXoaNV {
            get {
                return ResourceManager.GetString("txtLichSuXoaNV", resourceCulture);
            }
        }
    }
}
