//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Xml.Serialization;

namespace AppSach
{
    [DesignerCategory("code"), HelpKeyword("vs.data.DataSet"), Serializable, ToolboxItem(true), XmlRoot("Sach"), XmlSchemaProvider("GetTypedDataSetSchema")]
    public class SachBase
    {
    }
}